print("Rezept auswählen:")
print("(1) Pfannkuchen")
print("(2) Waffeln")
print("(3) Käsekuchen")
selection = input("Auswahl eingeben: ")

if selection == '1':
    print("")
    print("Rezept: Pfannkuchen")
    print("")
    print("Zutaten:")
    print("- 2 Eier")
    print("- 200ml Milch")
    print("- 1 Prise Zucker")
    print("- 1 Prise Salz")
    print("- 200g Mehl")
    print("- 60ml Mineralwasser")
    print("- Etwas Speiseöl zum Ausbacken")
    input("Drücke eine Beliebige Taste um Fortzufahren...")
if selection == '2':
    print("")
    print("Rezept: Waffeln")
    input("Drücke eine Beliebige Taste um Fortzufahren...")
if selection == '3':
    print("")
    print("Rezept: Käsekuchen")
    input("Drücke eine Beliebige Taste um Fortzufahren...")
